name: time_capsule
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.3.6
  
  device_preview: ^1.3.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  fake_cloud_firestore: ^3.0.3


flutter:


  uses-material-design: true


