// Mocks generated by Mockito 5.4.6 from annotations
// in time_capsule/test/widgets/public_folders_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:time_capsule/models/folder_model.dart' as _i5;
import 'package:time_capsule/models/shared_folder_data.dart' as _i7;
import 'package:time_capsule/models/shared_folder_notification_model.dart'
    as _i9;
import 'package:time_capsule/models/user_profile.dart' as _i8;
import 'package:time_capsule/services/folder_service.dart' as _i3;
import 'package:time_capsule/services/user_profile_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T1 extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T1> {
  _FakeDocumentReference_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_1 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FolderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderService extends _i1.Mock implements _i3.FolderService {
  MockFolderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createFolder(_i5.FolderModel? folder) =>
      (super.noSuchMethod(
            Invocation.method(#createFolder, [folder]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createFolder, [folder]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateFolder(String? folderId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateFolder, [folderId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolder, [folderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.FolderModel>> streamFolders({
    required String? userId,
    String? parentFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamFolders, [], {
              #userId: userId,
              #parentFolderId: parentFolderId,
            }),
            returnValue: _i4.Stream<List<_i5.FolderModel>>.empty(),
          )
          as _i4.Stream<List<_i5.FolderModel>>);

  @override
  _i4.Future<_i5.FolderModel?> getFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getFolder, [folderId]),
            returnValue: _i4.Future<_i5.FolderModel?>.value(),
          )
          as _i4.Future<_i5.FolderModel?>);

  @override
  _i4.Future<void> updateFolderName(String? folderId, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateFolderName, [folderId, newName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFolders(List<String>? folderIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolders, [folderIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> createSharedFolder(
    _i5.FolderModel? folder,
    List<String>? contributorIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSharedFolder, [folder, contributorIds]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createSharedFolder, [
                  folder,
                  contributorIds,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> convertToSharedFolder(
    String? folderId,
    List<String>? contributorIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#convertToSharedFolder, [
              folderId,
              contributorIds,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> inviteContributors(
    String? folderId,
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inviteContributors, [folderId, userIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> notifyContributorAdded(
    String? folderId,
    String? contributorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notifyContributorAdded, [
              folderId,
              contributorId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeContributor(String? folderId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeContributor, [folderId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> lockFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#lockFolder, [folderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unlockFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockFolder, [folderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.SharedFolderData?> getSharedFolderData(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedFolderData, [folderId]),
            returnValue: _i4.Future<_i7.SharedFolderData?>.value(),
          )
          as _i4.Future<_i7.SharedFolderData?>);

  @override
  _i4.Future<bool> canUserContribute(String? folderId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canUserContribute, [folderId, userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> canUserView(String? folderId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canUserView, [folderId, userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i8.UserProfile>> getFolderContributors(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getFolderContributors, [folderId]),
            returnValue: _i4.Future<List<_i8.UserProfile>>.value(
              <_i8.UserProfile>[],
            ),
          )
          as _i4.Future<List<_i8.UserProfile>>);

  @override
  _i4.Stream<List<_i5.FolderModel>> streamAccessibleFolders({
    required String? userId,
    String? parentFolderId,
    bool? includeShared = true,
    bool? includePublic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAccessibleFolders, [], {
              #userId: userId,
              #parentFolderId: parentFolderId,
              #includeShared: includeShared,
              #includePublic: includePublic,
            }),
            returnValue: _i4.Stream<List<_i5.FolderModel>>.empty(),
          )
          as _i4.Stream<List<_i5.FolderModel>>);

  @override
  _i4.Stream<List<_i5.FolderModel>> streamUserAccessibleFolders(
    String? userId, {
    String? parentFolderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamUserAccessibleFolders,
              [userId],
              {#parentFolderId: parentFolderId},
            ),
            returnValue: _i4.Stream<List<_i5.FolderModel>>.empty(),
          )
          as _i4.Stream<List<_i5.FolderModel>>);

  @override
  _i4.Future<void> makePublic(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#makePublic, [folderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> makePrivate(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#makePrivate, [folderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.FolderModel>> getPublicFolders({
    int? limit = 20,
    _i2.DocumentSnapshot<Object?>? startAfter,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicFolders, [], {
              #limit: limit,
              #startAfter: startAfter,
              #searchQuery: searchQuery,
            }),
            returnValue: _i4.Future<List<_i5.FolderModel>>.value(
              <_i5.FolderModel>[],
            ),
          )
          as _i4.Future<List<_i5.FolderModel>>);

  @override
  _i4.Stream<List<_i5.FolderModel>> streamPublicFolders({
    int? limit = 20,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamPublicFolders, [], {
              #limit: limit,
              #searchQuery: searchQuery,
            }),
            returnValue: _i4.Stream<List<_i5.FolderModel>>.empty(),
          )
          as _i4.Stream<List<_i5.FolderModel>>);

  @override
  _i4.Future<bool> isFolderPublic(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#isFolderPublic, [folderId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i9.SharedFolderNotification>> getSharedFolderNotifications(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedFolderNotifications, [userId]),
            returnValue: _i4.Future<List<_i9.SharedFolderNotification>>.value(
              <_i9.SharedFolderNotification>[],
            ),
          )
          as _i4.Future<List<_i9.SharedFolderNotification>>);

  @override
  _i4.Stream<List<_i9.SharedFolderNotification>>
  streamSharedFolderNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#streamSharedFolderNotifications, [userId]),
            returnValue: _i4.Stream<List<_i9.SharedFolderNotification>>.empty(),
          )
          as _i4.Stream<List<_i9.SharedFolderNotification>>);

  @override
  _i4.Future<void> markNotificationAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnreadNotificationCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationCount, [userId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i10.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createUserProfile(
    String? userId,
    String? username,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [userId, username, email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i8.UserProfile?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i8.UserProfile?>.value(),
          )
          as _i4.Future<_i8.UserProfile?>);

  @override
  _i4.Future<void> updateUsername(String? userId, String? newUsername) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [userId, newUsername]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isUsernameAvailable(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameAvailable, [username]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateProfilePicture(String? userId, _i11.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [userId, imageFile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [currentPassword, newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i8.UserProfile?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i4.Future<_i8.UserProfile?>.value(),
          )
          as _i4.Future<_i8.UserProfile?>);

  @override
  _i4.Future<void> updateUserProfile(
    String? userId, {
    String? email,
    String? username,
    String? profilePictureUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserProfile,
              [userId],
              {
                #email: email,
                #username: username,
                #profilePictureUrl: profilePictureUrl,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProfilePicture(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfilePicture, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i2.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_0<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i2.DocumentReference<T>);

  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_1(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}
