// Mocks generated by Mockito 5.4.4 from annotations
// in time_capsule/test/integration/public_folder_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:time_capsule/models/folder_model.dart' as _i6;
import 'package:time_capsule/models/media_model.dart' as _i7;
import 'package:time_capsule/services/folder_service.dart' as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_1 extends _i1.SmartFake implements _i2.UserCredential {
  _FakeUserCredential_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolderModel_3 extends _i1.SmartFake implements _i6.FolderModel {
  _FakeFolderModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i2.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User? get currentUser => (super.noSuchMethod(Invocation.getter(#currentUser)) as _i2.User?);

  @override
  _i4.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i2.User?>.empty(),
      ) as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i3.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: '',
      ) as String);

  @override
  String? get email => (super.noSuchMethod(Invocation.getter(#email)) as String?);

  @override
  String? get displayName => (super.noSuchMethod(Invocation.getter(#displayName)) as String?);

  @override
  String? get photoURL => (super.noSuchMethod(Invocation.getter(#photoURL)) as String?);
}

/// A class which mocks [FolderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderService extends _i1.Mock implements _i5.FolderService {
  MockFolderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.FolderModel> getFolder(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getFolder,
          [folderId],
        ),
        returnValue: _i4.Future<_i6.FolderModel>.value(_FakeFolderModel_3(
          this,
          Invocation.method(
            #getFolder,
            [folderId],
          ),
        )),
      ) as _i4.Future<_i6.FolderModel>);

  @override
  _i4.Future<List<_i7.MediaModel>> getMediaInFolder(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #getMediaInFolder,
          [folderId],
        ),
        returnValue: _i4.Future<List<_i7.MediaModel>>.value(<_i7.MediaModel>[]),
      ) as _i4.Future<List<_i7.MediaModel>>);

  @override
  _i4.Future<List<_i6.FolderModel>> getPublicFolders({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicFolders,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i6.FolderModel>>.value(<_i6.FolderModel>[]),
      ) as _i4.Future<List<_i6.FolderModel>>);

  @override
  _i4.Future<List<_i6.FolderModel>> searchPublicFolders(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPublicFolders,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.FolderModel>>.value(<_i6.FolderModel>[]),
      ) as _i4.Future<List<_i6.FolderModel>>);

  @override
  _i4.Future<_i6.FolderModel> makePublic(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #makePublic,
          [folderId],
        ),
        returnValue: _i4.Future<_i6.FolderModel>.value(_FakeFolderModel_3(
          this,
          Invocation.method(
            #makePublic,
            [folderId],
          ),
        )),
      ) as _i4.Future<_i6.FolderModel>);

  @override
  _i4.Future<_i6.FolderModel> makePrivate(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #makePrivate,
          [folderId],
        ),
        returnValue: _i4.Future<_i6.FolderModel>.value(_FakeFolderModel_3(
          this,
          Invocation.method(
            #makePrivate,
            [folderId],
          ),
        )),
      ) as _i4.Future<_i6.FolderModel>);
}